
services:                       # блок, описывающий каждый отдельный сервис
  postgres:                     # имя сервиса 
    image: daariopa/postgres:16.2             
    restart: always
    environment:                # список переменных окружения
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_HOST=postgres
    volumes:
      - ./src/services/database/init.sql:/docker-entrypoint-initdb.d/init.sql  #Инициализация базы данных со всеми сценариями SQL в каталоге базы данных на хост-компьютере.
      - postgres:/var/lib/postgres/data  # путь к каталогу контейнера для хранения файлов базы данных 
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - overlay_network

  rabbitmq:                     
    image: daariopa/devops_7-1-rabbitmq-1:3
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - overlay_network
          
  booking-service:
    image: daariopa/devops_7-1-booking-service:1.2
    environment:                
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reservations_db
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_QUEUE_NAME=messagequeue
      - RABBIT_MQ_EXCHANGE=messagequeue-exchange
      - HOTEL_SERVICE_HOST=hotel-service
      - HOTEL_SERVICE_PORT=8082
      - PAYMENT_SERVICE_HOST=payment-service
      - PAYMENT_SERVICE_PORT=8084
      - LOYALTY_SERVICE_HOST=loyalty-service
      - LOYALTY_SERVICE_PORT=8085
    depends_on:                  # ждать, когда будут готовы к работе другие сервисы
      - postgres
      - rabbitmq
    networks:
      - overlay_network
    
  gateway-service:
    image: daariopa/devops_7-1-gateway-service:1.2
    environment: 
    - SESSION_SERVICE_HOST=session-service
    - SESSION_SERVICE_PORT=8081
    - HOTEL_SERVICE_HOST=hotel-service
    - HOTEL_SERVICE_PORT=8082
    - BOOKING_SERVICE_HOST=booking-service
    - BOOKING_SERVICE_PORT=8083
    - PAYMENT_SERVICE_HOST=payment-service
    - PAYMENT_SERVICE_PORT=8084
    - LOYALTY_SERVICE_HOST=loyalty-service
    - LOYALTY_SERVICE_PORT=8085
    - REPORT_SERVICE_HOST=report-service
    - REPORT_SERVICE_PORT=8086
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - overlay_network

  hotel-service:
    image: daariopa/devops_7-1-hotel-service:1.2
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotels_db
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - overlay_network

  loyalty-service:
    image: daariopa/devops_7-1-loyalty-service:1.2
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=balances_db
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - overlay_network

  payment-service:
    image: daariopa/devops_7-1-payment-service:1.2
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments_db
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - overlay_network

  report-service:
    image: daariopa/devops_7-1-report-service:1.2
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=statistics_db
      - RABBIT_MQ_HOST=rabbitmq
      - RABBIT_MQ_PORT=5672
      - RABBIT_MQ_USER=guest
      - RABBIT_MQ_PASSWORD=guest
      - RABBIT_MQ_QUEUE_NAME=messagequeue
      - RABBIT_MQ_EXCHANGE=messagequeue-exchange
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - overlay_network

  session-service:
    image: daariopa/devops_7-1-session-service:1.2
    environment:                
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users_db
    depends_on:                 
      - postgres
      - rabbitmq
    networks:
      - overlay_network

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 8081:8081
      - 8087:8087
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - gateway-service
      - session-service
    networks:
      - overlay_network
    
     
volumes:
  postgres: 
networks:
  overlay_network:
    driver: overlay     

